In [54]:
import numpy as np

In [55]:
#1.Introduction to Numpy and Array Creation
#1.a
arr1 = np.array([10,20,30,40,50])
print("1D Array: ")
print(arr1)

1D Array: 
[10 20 30 40 50]


In [56]:
#1.b
arr2 = np.zeros((2,3))
print("2x3 0 array: ")
print(arr2)

2x3 0 array: 
[[0. 0. 0.]
 [0. 0. 0.]]


In [57]:
#1.c
arr3 = np.arange(0,101,5)
print("Number from 0 to 100 with space 5: ")
print(arr3)

Number from 0 to 100 with space 5: 
[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


In [58]:
#2.a
arr4 = np.array([5,10,15,20,25,30])
newarr4 = arr4[:3]
print("First 3 elements: ")
print(newarr4)

First 3 elements: 
[ 5 10 15]


In [59]:
#2.b
arr4 = np.array([5,10,15,20,25,30])
narr4 = arr4[1::2]
print("Extracted every 2nd elements: ")
print(narr4)

Extracted every 2nd elements: 
[10 20 30]


In [60]:
#2.c
arr4[3]=50
print("After changing the 4th element to 50: ")
print(arr4)

After changing the 4th element to 50: 
[ 5 10 15 50 25 30]


In [61]:
#3.a
arr5 = np.arange(1,13)
print("1D array from 1 to 12")
print(arr5)


1D array from 1 to 12
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [62]:
#3.b
arr5 = arr5.reshape(3,4)
print("Reshaped array: ")
print(arr5)

Reshaped array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [63]:
#4.a
arr6 = np.array([1,2,3,4,5])
print("After adding 10 to each element: ")
print(np.add(arr6,10))

After adding 10 to each element: 
[11 12 13 14 15]


In [64]:
#4.b
print("After multiplying 3 to each element: ")
print(np.multiply(arr6,3))

After multiplying 3 to each element: 
[ 3  6  9 12 15]


In [65]:
#4.c
print("After squaring the elements: ")
for i in range(0,len(arr6)):
    print(arr6[i]**2)

After squaring the elements: 
1
4
9
16
25


In [66]:
#5.a
temp = np.array([30,32,31,29,28,33,34])
print(f"Mean temperature: {np.sum(temp)/len(temp)} ")

Mean temperature: 31.0 


In [67]:
#5.b
print(f"Minimum temperature: {np.min(temp)} \nMaximum temperature: {np.max(temp)}")

Minimum temperature: 28 
Maximum temperature: 34


In [68]:
#5.c
print(f"Sum of the temperatures: {np.sum(temp)}")

Sum of the temperatures: 217


In [69]:
#6.a
product = np.array([200,220,250,270,300,150,160,170,180,200])
product.resize((2,5))
print(product)
print(f"Total Sales for first product: {np.sum(product[0][0:])} ")
print(f"Total Sales for second product: {np.sum(product[1][0:])} ")


[[200 220 250 270 300]
 [150 160 170 180 200]]
Total Sales for first product: 1240 
Total Sales for second product: 860 


In [70]:
#6.b
for i in range(5):
    val1 = product[0][i]
    val2 = product[1][i]
    avg = (val1+val2)/2
    print(f"Average sales on Day-{i+1}: {avg}")

Average sales on Day-1: 175.0
Average sales on Day-2: 190.0
Average sales on Day-3: 210.0
Average sales on Day-4: 225.0
Average sales on Day-5: 250.0


In [71]:
#6.c
maxp1 = np.max(product[0][0:])
maxp2 = np.max(product[1][0:])
print(f"Highest sales for Product-1 on Day-{np.where(product[0][0:]==maxp1)[0]}")
print(f"Highest sales for Product-2 on Day-{np.where(product[1][0:]==maxp2)[0]}")


Highest sales for Product-1 on Day-[4]
Highest sales for Product-2 on Day-[4]
